apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: driftguard
  labels:
    app: test-app
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
        component: backend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: ENVIRONMENT
          value: "development"
        - name: LOG_LEVEL
          value: "info"
      restartPolicy: Always 