server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  shutdown_timeout: 30s

database:
  host: localhost
  port: 27017
  dbname: DriftGuard
  user: ""

kubernetes:
  config_path: "C:/Users/shrey/.kube/config"
  context: "docker-desktop"
  namespaces: ["driftguard"]
  resources:
    - deployments
    - services
    - configmaps
    - secrets
  labels: {}

git:
  # Use file:// URL for a local Windows path and forward slashes
  repository_url: "file:///E:/DriftGuard/DriftGuard/dummy-k8s-repo"
  # Ensure this branch actually exists in the repo
  default_branch: main
  clone_timeout: 5m
  pull_timeout: 2m

environments:
  - name: development
    description: Development environment
    labels:
      env: dev
    k8s_context: dev-cluster

logging:
  level: info
  format: json
  output_path: ""
